---
abstract: 'Moo eXtension for initializing objects from config file'
author:
  - 'Jens Rehsack <rehsack@cpan.org>'
build_requires:
  Cwd: '0'
  File::Basename: '0'
  File::Spec: '0'
  JSON: '0'
  Test::More: '0.9'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.02, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooX-ConfigFromFile
no_index:
  directory:
    - t
    - inc
requires:
  Config::Any: '0'
  File::Find::Rule: '0.30'
  FindBin: '0'
  Moo: '1.003'
  MooX::File::ConfigDir: '0.002'
  perl: v5.8.1
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=MooX-ConfigFromFile
  homepage: https://metacpan.org/release/MooX-ConfigFromFile
  license: http://dev.perl.org/licenses/
  repository: https://github.com/rehsack/MooX-ConfigFromFile
version: '0.005'
